spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.249.14:3306/blog?useEncoding=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
#    url: jdbc:mysql://172.17.0.2:3306/blog?useEncoding=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Mer@123
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10


  #    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 12
#      connection-timeout: 20000
#      max-lifetime: 1200000
#      idle-timeout: 300000
#      connection-test-query: SELECT 1
#      pool-name: BlogHikariPool



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    ehcache:
      config: classpath:ehcache.xml

logging:
  file: log/blog-dev.log
  level:
    root: info
    com.mercer.myblog: debug
server:
  port: 7777